### ISSUE TITLE
Activer le menu pour Sirtaki

### ISSUE THREAD

**Issue by tjobit** [gfroidcourt/iut-onboarding#105]
Pendant un moment le site du crous n'affichait plus le menu du Sirtaki donc on l'avait commenté mais ça semble être bon.

Dans [getCrousMenus.js](https://github.com/gfroidcourt/iut-onboarding/blob/main/functions/getCrousMenus.js) faut décommenter la ligne et voir si le scraping est toujours bon pour le site (les menus du sirtaki et du space avaient le même html a une époque mais bon...)

**Comment by tjobit** [comment]
Faut check si ce que je dis est bon, ils ont l'air de communiquer le menu pour le jour même, demain il y'a pas le menu encore (et il y'a écrit fermé pour cause de travaux???)

**Comment by Xabi08YT** [comment]
Ouais donc bon, pas fou. Je ferais un système qui l'affichage s'il arrive a le get et sinon on affiche pas

**Comment by Xabi08YT** [comment]
Pull Request Incoming avec un affichage "intelligent". Donc normalement, a tester dans le cas pratique, mais si le menu n'est pas trouvable la carte de menu en question ne s'affiche pas.
