### ISSUE TITLE
Gérer les cours de TP via l'ID de TP

### ISSUE THREAD

**Issue by gfroidcourt** [gfroidcourt/iut-onboarding#55]

**Comment by celian-rib** [comment]
Une idée de ce que c'est que cette issue @gfroidcourt  ?

**Comment by gfroidcourt** [comment]
> Une idée de ce que c'est que cette issue @gfroidcourt ?

C'est pas le bon titre. Il y a un id en plus qui est les id de promotion (pour les amphis) qui ne sont pas géré actuellement

**Comment by gfroidcourt** [comment]
Enfin je pense que c'est ça

**Comment by celian-rib** [comment]
Duplicate de #51
